### ISSUE TITLE
[SR]프로젝트 기획 및 범위 설정

### ISSUE THREAD

**Issue by leo-labbb** [codestates/BaedalDutch#1]
### ISSUE
- Group: `sr`
- Type: 
- Detail: 

### TODO
- [x] 프로젝트명 & 팀 규칙 설정
- [x] 프로젝트 기획 및 범위 설정
- [x] 위키 및 Requirements 작성

### Estimated time
>시간을 수정하세요 
`3h`

### Labels
- Estimated time: `E: 3h`
- Group : `sr`
- Sprint: Sprint_NUM
- Urgency: `Middle`
