### ISSUE TITLE
[Task]파티 정보 수정, 삭제, 모집 마감 구현

### ISSUE THREAD

**Issue by leo-labbb** [codestates/BaedalDutch#13]
### ISSUE
- Group: `server`
- Type: `feature`
- Detail: 

### TODO
- [x] 토큰 확인 후 파티의 정보 업데이트하기
- [x] 토큰 확인 후 파티의 정보 삭제하기
- [x] 파티글 작성자가 마감 버튼을 눌렀을 때 모집 마감하기

### Estimated time
>시간을 수정하세요 
`3h`

### Labels
- Estimated time: `E: 3h`
- Group : `server`
- Sprint: Sprint_1
- Urgency: `Middle`
