### ISSUE TITLE
[SR]와이어프레임, DB 스키마, API 문서, 초기 개발환경 세팅

### ISSUE THREAD

**Issue by leo-labbb** [codestates/BaedalDutch#2]
### ISSUE
- Group: `sr`
- Type: `feature`, `bug`, `delete`
- Detail: 

### TODO
- [x] 프론트엔드: 와이어프레임
- [x] 백엔드: DB 스키마, API 문서 작성
- [x] Project Git Flow 구축
- [x] 초기 개발환경 세팅

### Estimated time
>시간을 수정하세요 
`3h`

### Labels
- Estimated time: `E: 3h`
- Group : `client`, `server`
- Sprint: Sprint_NUM
- Urgency:  `Middle`
